# Generated by Django 4.2.3 on 2023-07-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmodel',
            name='status_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='status_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='status_uz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='task_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='task_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='task_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_en',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_ru',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_uz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
