# Generated by Django 4.2.3 on 2023-07-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolistmodel_status_en_todolistmodel_status_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistmodel',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='status_uz',
        ),
    ]
